wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1657443960
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      4: 3.8.13
      5: 0.12.20
      8:
      - 4
      - 5
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 32
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: ram
cfg:
  desc: null
  value: ''
cos_lr:
  desc: null
  value: false
data:
  desc: null
  value: /Users/shauntoh/Documents/GitHub/yolov5/data/lta_data_3.yaml
data_dict:
  desc: null
  value:
    names:
    - 0_person_helmet_vest
    - 1_person_helmet
    - 2_person_vest
    - 3_motorcycle
    - 4_person
    - 5_bus
    - 6_train
    - 7_truck
    - 8_boat
    - 9_traffic light
    - 10_fire hydrant
    - 11_stop sign
    - 12_parking meter
    - 13_bench
    - 14_bird
    - 15_cat
    - 16_dog
    - 17_rat
    - 18_excavator
    - 19_crane
    - 20_baricade
    - 21_elephant
    - 22_bear
    - 23_zebra
    - 24_bicycle
    - 25_backpack
    - 26_umbrella
    - 27_motorbike
    - 28_lorry
    - 29_ladder_a
    - 30_harness
    - 31_skis
    - 32_person_harness
    - 33_platform_ladder
    - 34_harness_hook
    nc: 35
    path: ./Train_Images_2
    test: /Users/shauntoh/Documents/GitHub/yolov5/Train_Images_2/test
    train: /Users/shauntoh/Documents/GitHub/yolov5/Train_Images_2/train
    val: /Users/shauntoh/Documents/GitHub/yolov5/Train_Images_2/val
device:
  desc: null
  value: cpu
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 300
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value:
  - 0
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.01
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 640
label_smoothing:
  desc: null
  value: 0.0
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
noplots:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
optimizer:
  desc: null
  value: SGD
patience:
  desc: null
  value: 100
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/exp48
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: yolov5s.pt
workers:
  desc: null
  value: 8
